#include "ALL.H"

motorst Motorst1, Motorst2; // Ez nem hasznalando
motorst *Pmot1 = &Motorst1, *Pmot2 = &Motorst2;

double Elszakadasisebhat, Belsosav, G;
double Talppontegybeolvadasitav;

double Ugroturelem;
double Vegenvaras;

double Dr, Sr;

double Fejsugar;

double Objektumsugar = 0.4;

// Hajszalnyival kisebb rigidbody.sugarnal, hogy kirajzolasnal ne logjon foldbe:
double Kerekrajzsugar = 0.395;

double Kord2x, Kord2y, Kord4x, Kord4y,
    Kord5y; // Ez az utolso vezeto helye

double Arany, Aranyrec;

/* Eredeti szamitas play.cpp-bol:
Arany = 100.0;
Arany *= Displaysizex/320.0;
Arany *= fakt;
Aranyx = Arany*320.0/640.0;
Aranyy = Aranyx*Displaysizey/Displaysizex*(640.0/480.0);*/

int Viewzoom = 10;

void initmotor(motorst* pmot) {
    pmot->hatra_f = 0;
    pmot->hatra_h = 0;
    pmot->gravirany = 1;
    pmot->voltfek = 0;
    // pmot->labalfa = 0.0; Bicigli

    // Kor1:
    pmot->kor1.rotation = 0.0;
    pmot->kor1.angular_velocity = 0.0;
    pmot->kor1.radius = 0.3;
    pmot->kor1.mass = 200; // 100;
    // inertia = mass * r*r;
    pmot->kor1.inertia = 200.0 * 0.55 * 0.55;
    pmot->kor1.r = vekt2(2.75, 3.6);
    pmot->kor1.v = vekt2(0, 0);

    // Kor2:
    pmot->kor2.rotation = 0.0; // 30
    pmot->kor2.angular_velocity = 0.0;
    pmot->kor2.radius = 0.4;
    pmot->kor2.mass = 10;
    pmot->kor2.inertia = 0.32;
    pmot->kor2.r = vekt2(1.9, 3.0);
    pmot->kor2.v = vekt2(0, 0);

    // Kor4:
    pmot->kor4.rotation = 0.0; // 40
    pmot->kor4.angular_velocity = 0.0;
    pmot->kor4.radius = 0.4;
    pmot->kor4.mass = 10;
    pmot->kor4.inertia = 0.32;
    pmot->kor4.r = vekt2(3.6, 3.0);
    pmot->kor4.v = vekt2(0, 0);

    pmot->vezetor = vekt2(2.75, 4.04);
    pmot->vezetov = vekt2(0.0, 0.0);
}

void initadatok(void) {
    initmotor(Pmot1);
    initmotor(Pmot2);

    double fakt = 0.48; // 0.54; volt mar 28 is
    if (State->minibike) {
        fakt = 0.30;
    }

    Arany = 100.0 * fakt;
    Aranyrec = 1.0 / Arany;

    // Viewzoom = 0.28*Arany*0.5;
    Viewzoom = 0.42 * Arany * 0.5;

    Elszakadasisebhat = 0.01;
    Belsosav = 0.005; // uj
    // Belsosav = 0.02; // regi
    G = 10.0; // nehezsegi gyorsulas: a [m/s^2]
    Talppontegybeolvadasitav = 0.1;

    // Ugroturelem = 0.2;
    Ugroturelem = 0.4;
    Vegenvaras = 1.0;

    Dr = 10000.0; // rudban fuggoleges modulus: F/l [N/m]
    Sr = 1000.0;  // rudban mozgasi ellenallas: F/v [N*s/m]

    Fejsugar = 0.238; // 0.26;

    vekt2 vtmp = Pmot1->kor2.r - Pmot1->kor1.r;
    Kord2x = vtmp.x;
    Kord2y = vtmp.y;
    vtmp = Pmot1->kor4.r - Pmot1->kor1.r;
    Kord4x = vtmp.x;
    Kord4y = vtmp.y;

    Kord5y = Pmot1->vezetor.y - Pmot1->kor1.r.y;
}

/*static double atmeretez( void ) {
    FILE* h = fopen( "size.inf", "rt" );
    if( !h )
        return 1.0;
    long meret = 1000;
    if( fscanf( h, "%ld", &meret ) != 1 ) {
        fclose( h );
        return 1.0;
    }
    fclose( h );
    if( meret < 100 )
        meret = 100;
    if( meret > 10000 )
        meret = 10000;
    return (double)meret/1000.0;
} */

// reorder.h-ban friend-kent vannak deklaralva mar:
// pgazhatra-ba beepiti betoltvet:
void berakrecbehosszat(recorder* prec) {
    if (prec->betoltve < 80) {
        return;
    }
    unsigned int beirando = prec->betoltve;
    for (int i = 0; i < 32; i++) {
        prec->pgazhatra[40 + i] = prec->pgazhatra[40 + i] & 127;
        if (beirando & 1) {
            prec->pgazhatra[40 + i] += 128;
        }
        beirando = beirando >> 1;
    }
}

// pgazhatra alapjan ellenorzi hosszt:
// Ezt vegleges verziobol kiszedjuk, mert ezt csak mi ellenorizzuk Csabival:
/*int jorechossza( recorder* prec ) {
    if( prec->betoltve < 80 )
        return 1;
    unsigned int szam = 0;
    for( int i = 0; i < 32; i++ ) {
        szam *= 2;
        if( prec->pgazhatra[40+31-i] & 128 )
            szam += 1;
    }
    if( szam == prec->betoltve )
        return 1;
    else
        return 0;
} */
